apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book
  name: book
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book # pod specs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: book # name of the pod
    spec:
      containers:
      - image: davidhalascsak/book-service:0.0.1
        imagePullPolicy: IfNotPresent # Always
        name: book-service
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: book
  name: book
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: book # name of the pod to pair with a port
  sessionAffinity: None
  type: LoadBalancer