apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book
  name: book
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - image: gcr.io/bookshop-416221/github.com/davidhalascsak/bookservice
          imagePullPolicy: IfNotPresent
          name: bookservice
          envFrom:
            - secretRef:
                name: connections
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: book
  name: book-hpa-wokl
  namespace: default
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: book
  name: book-service
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: book
  sessionAffinity: None
  type: LoadBalancer

      