apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book
  name: book
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - image: gcr.io/weighty-psyche-421907/github.com/davidhalascsak/bookservice
          imagePullPolicy: IfNotPresent
          name: bookservice
          env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
               name: connections
               key: mongodb_username
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: connections
                key: mongodb_password
          readinessProbe:
            httpGet:
              port: 8100
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8100
              path: /actuator/health/liveness
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: book
  name: book-hpa-wokl
  namespace: shop
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: book
  name: book-service
  namespace: shop
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: book
  type: LoadBalancer